name: phone_formatter
description: "A simple and flexible phone number formatter for Flutter, supporting mask and set of masks (dynamic country code detection)."
version: 0.0.1
homepage: shoshi.tech

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
